name: second
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  jwt_decoder: ^2.0.1
  mobile_scanner: ^4.0.0
  url_launcher: ^6.3.2

  # Firebase & Notifications
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

  # Google Sign-In
  google_sign_in: ^6.2.1
  firebase_auth: ^5.0.0

  # Video Player
  video_player: ^2.8.6

  # For date formatting
  intl: ^0.19.0

  # For AI Chat (Text input, Audio output ONLY)
  just_audio: ^0.9.36
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
